package labs;

import java.util.UUID;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

@Entity
public class Album {

    // Autogenerated UUID for primary key.
    // this is a preferred ID type in Cloud Spanner,
    // as it avoids hotspots as the system divides data
    // among servers by key ranges.
    @GeneratedValue
    UUID albumId;

    Singer singer;

    String albumTitle;

    public Album() {

    }

    public Album(Singer singer, String albumTitle) {
        this.singer = singer;
        this.albumTitle = albumTitle;
    }

    
}